 program RPFood_VCL;

uses
  System.SysUtils,
  IWRtlFix,
  Forms,
  IWStart,
  ServerController in 'Infra\ServerController.pas' {IWServerController: TIWServerControllerBase},
  UserSessionUnit in 'Infra\UserSessionUnit.pas' {IWUserSession: TIWUserSessionBase},
  RPFood.View.ADMIN.Login in 'Source\View\RPFood.View.ADMIN.Login.pas' {FrmADMINLogin: TIWAppForm},
  RPFood.Controller in 'Source\Controller\RPFood.Controller.pas',
  RPFood.Entity.Cliente in 'Source\Model\Entity\RPFood.Entity.Cliente.pas',
  RPFood.Entity.Classes in 'Source\Model\Entity\RPFood.Entity.Classes.pas',
  RPFood.DAO.Base in 'Source\Model\DAO\RPFood.DAO.Base.pas',
  RPFood.DAO.Cliente in 'Source\Model\DAO\RPFood.DAO.Cliente.pas',
  RPFood.DAO.Factory in 'Source\Model\DAO\RPFood.DAO.Factory.pas',
  RPFood.Entity.Categoria in 'Source\Model\Entity\RPFood.Entity.Categoria.pas',
  RPFood.Entity.Produto in 'Source\Model\Entity\RPFood.Entity.Produto.pas',
  RPFood.DAO.Categoria in 'Source\Model\DAO\RPFood.DAO.Categoria.pas',
  RPFood.DAO.Produto in 'Source\Model\DAO\RPFood.DAO.Produto.pas',
  RPFood.View.ADMIN.Padrao in 'Source\View\RPFood.View.ADMIN.Padrao.pas' {FrmADMINPadrao: TIWAppForm},
  RPFood.View.Index in 'Source\View\RPFood.View.Index.pas' {FrmIndex: TIWAppForm},
  RPFood.Entity.Venda in 'Source\Model\Entity\RPFood.Entity.Venda.pas',
  RPFood.Entity.Opcional in 'Source\Model\Entity\RPFood.Entity.Opcional.pas',
  RPFood.DAO.ProdutoOpcional in 'Source\Model\DAO\RPFood.DAO.ProdutoOpcional.pas',
  RPFood.Entity.ProdutoOpcional in 'Source\Model\Entity\RPFood.Entity.ProdutoOpcional.pas',
  RPFood.DAO.Opcional in 'Source\Model\DAO\RPFood.DAO.Opcional.pas',
  RPFood.View.EsqueciMinhaSenha in 'Source\View\RPFood.View.EsqueciMinhaSenha.pas' {FrmEsqueciMinhaSenha: TIWAppForm},
  RPFood.Utils in 'Source\Model\Utils\RPFood.Utils.pas',
  RPFood.Components in 'Source\Model\Components\RPFood.Components.pas',
  RPFood.Service.EsqueciMinhaSenha in 'Source\Model\Service\EsqueciMinhaSenha\RPFood.Service.EsqueciMinhaSenha.pas',
  RPFood.Service in 'Source\Model\Service\RPFood.Service.pas',
  RPFood.Resources in 'Infra\RPFood.Resources.pas',
  RPFood.Entity.FormaPagamento in 'Source\Model\Entity\RPFood.Entity.FormaPagamento.pas',
  RPFood.DAO.FormaPagamento in 'Source\Model\DAO\RPFood.DAO.FormaPagamento.pas',
  RPFood.DAO.Venda in 'Source\Model\DAO\RPFood.DAO.Venda.pas',
  RPFood.Service.Venda in 'Source\Model\Service\Venda\Pedido\RPFood.Service.Venda.pas',
  RPFood.DAO.VendaItem in 'Source\Model\DAO\RPFood.DAO.VendaItem.pas',
  RPFood.DAO.VendaItemOpcional in 'Source\Model\DAO\RPFood.DAO.VendaItemOpcional.pas',
  RPFood.DAO.Conexao in 'Source\Model\DAO\RPFood.DAO.Conexao.pas',
  RPFood.Entity.Pedido in 'Source\Model\Entity\RPFood.Entity.Pedido.pas',
  RPFood.View.PedidoDetalheItem in 'Source\View\RPFood.View.PedidoDetalheItem.pas' {FrmPedidoDetalheItem: TIWAppForm},
  RPFood.View.Rotas in 'Source\View\RPFood.View.Rotas.pas',
  RPFood.View.VendaHistorico in 'Source\View\RPFood.View.VendaHistorico.pas' {FrmVendaHistorico: TIWAppForm},
  RPFood.View.ProdutosPorCategoria in 'Source\View\RPFood.View.ProdutosPorCategoria.pas' {FrmProdutosPorCategoria: TIWAppForm},
  RPFood.View.Pedido.Sessao in 'Source\View\RPFood.View.Pedido.Sessao.pas',
  RPFood.Entity.Endereco in 'Source\Model\Entity\RPFood.Entity.Endereco.pas',
  RPFood.DAO.Endereco in 'Source\Model\DAO\RPFood.DAO.Endereco.pas',
  RPFood.View.Pedido.Finalizar in 'Source\View\RPFood.View.Pedido.Finalizar.pas' {FrmPedidoFinalizar: TIWAppForm},
  RPFood.Components.JSON in 'Source\Model\Components\JSON\RPFood.Components.JSON.pas',
  RPFood.View.Erro404 in 'Source\View\RPFood.View.Erro404.pas' {FrmErro404: TIWAppForm},
  RPFood.View.Erro500 in 'Source\View\RPFood.View.Erro500.pas' {IWException: TIWAppForm},
  RPFood.View.ClienteEndereco in 'Source\View\RPFood.View.ClienteEndereco.pas' {FrmClienteEndereco: TIWAppForm},
  RPFood.Entity.Types in 'Source\Model\Entity\RPFood.Entity.Types.pas',
  RPFood.Entity.Empresa in 'Source\Model\Entity\RPFood.Entity.Empresa.pas',
  RPFood.DAO.Empresa in 'Source\Model\DAO\RPFood.DAO.Empresa.pas',
  RPFood.Service.Cliente in 'Source\Model\Service\Cliente\RPFood.Service.Cliente.pas',
  RPFood.DAO.ClienteEndereco in 'Source\Model\DAO\RPFood.DAO.ClienteEndereco.pas',
  RPFood.Entity.VendaEndereco in 'Source\Model\Entity\RPFood.Entity.VendaEndereco.pas',
  RPFood.Entity.VendaStatusLog in 'Source\Model\Entity\RPFood.Entity.VendaStatusLog.pas',
  RPFood.DAO.VendaStatusLog in 'Source\Model\DAO\RPFood.DAO.VendaStatusLog.pas',
  RPFood.DAO.VendaEndereco in 'Source\Model\DAO\RPFood.DAO.VendaEndereco.pas',
  RPFood.View.ClienteDados in 'Source\View\RPFood.View.ClienteDados.pas' {FrmClienteMeusDados: TIWAppForm},
  UserSessionUnitCliente in 'Infra\UserSessionUnitCliente.pas',
  RPFood.Entity.ADMIN.Usuario in 'Source\Model\Entity\RPFood.Entity.ADMIN.Usuario.pas',
  RPFood.DAO.ADMIN.Usuario in 'Source\Model\DAO\RPFood.DAO.ADMIN.Usuario.pas',
  UserSessionUnitADMIN in 'Infra\UserSessionUnitADMIN.pas',
  RPFood.View.Login in 'Source\View\RPFood.View.Login.pas' {FrmLogin: TIWAppForm},
  RPFood.View.Padrao in 'Source\View\RPFood.View.Padrao.pas' {FrmPadrao: TIWAppForm},
  RPFood.View.ADMIN.Index in 'Source\View\RPFood.View.ADMIN.Index.pas' {FrmADMINIndex: TIWAppForm},
  RPFood.View.ADMIN.Index2 in 'Source\View\RPFood.View.ADMIN.Index2.pas' {FrmADMINIndex2: TIWAppForm},
  RPFood.DAO.RelatorioVendas in 'Source\Model\DAO\RPFood.DAO.RelatorioVendas.pas',
  RPFood.Entity.RelatorioVendas in 'Source\Model\Entity\RPFood.Entity.RelatorioVendas.pas',
  RPFood.View.VendaHistoricoAdm in 'Source\View\RPFood.View.VendaHistoricoAdm.pas' {FrmVendaHistoricoAdm: TIWAppForm},
  RPFood.View.Pedido.Acompanhamento in 'Source\View\RPFood.View.Pedido.Acompanhamento.pas' {FrmPedidoAcompanhamento: TIWAppForm},
  RPFood.Service.Venda.ItemFracao in 'Source\Model\Service\Venda\Pedido\RPFood.Service.Venda.ItemFracao.pas',
  RPFood.Entity.ConfiguracaoAtendimento in 'Source\Model\Entity\RPFood.Entity.ConfiguracaoAtendimento.pas',
  RPFood.DAO.ConfiguracaoFuncionamento in 'Source\Model\DAO\RPFood.DAO.ConfiguracaoFuncionamento.pas',
  RPFood.Entity.TransferenciaImagens in 'Source\Model\Entity\RPFood.Entity.TransferenciaImagens.pas',
  RPFood.DAO.TransferenciaImagens in 'Source\Model\DAO\RPFood.DAO.TransferenciaImagens.pas',
  RPFood.Service.Imagem.Categoria in 'Source\Model\Service\Imagem\RPFood.Service.Imagem.Categoria.pas',
  RPFood.Service.Imagem in 'Source\Model\Service\Imagem\RPFood.Service.Imagem.pas',
  RPFood.Service.Imagem.Produto in 'Source\Model\Service\Imagem\RPFood.Service.Imagem.Produto.pas',
  RPFood.View.ClienteCadastro in 'Source\View\RPFood.View.ClienteCadastro.pas' {FrmClienteCadastro: TIWAppForm},
  RPFood.View.ProdutosTodasCategoria in 'Source\View\RPFood.View.ProdutosTodasCategoria.pas' {FrmProdutostodascategoria: TIWAppForm},
  RPFood.Service.Venda.Copia in 'Source\Model\Service\Venda\Copia\RPFood.Service.Venda.Copia.pas',
  RPFood.Service.Login.Cliente in 'Source\Model\Service\Login\RPFood.Service.Login.Cliente.pas',
  RPFood.View.Sobre in 'Source\View\RPFood.View.Sobre.pas' {FrmSobre: TIWAppForm},
  RPFood.Entity.ConfiguracaoRPFood in 'Source\Model\Entity\RPFood.Entity.ConfiguracaoRPFood.pas',
  RPFood.DAO.ConfiguracaoRPFood in 'Source\Model\DAO\RPFood.DAO.ConfiguracaoRPFood.pas',
  RPFood.Service.Imagem.Opcional in 'Source\Model\Service\Imagem\RPFood.Service.Imagem.Opcional.pas',
  RPFood.Entity.Bairro in 'Source\Model\Entity\RPFood.Entity.Bairro.pas',
  RPFood.DAO.Bairro in 'Source\Model\DAO\RPFood.DAO.Bairro.pas',
  RPFood.Entity.Happy_Hour in 'Source\Model\Entity\RPFood.Entity.Happy_Hour.pas',
  RPFood.DAO.Happy_Hour in 'Source\Model\DAO\RPFood.DAO.Happy_Hour.pas',
  RPFood.DAO.Promocao in 'Source\Model\DAO\RPFood.DAO.Promocao.pas',
  RPFood.Entity.RestricaoVenda in 'Source\Model\Entity\RPFood.Entity.RestricaoVenda.pas',
  RPFood.DAO.RestricaoVenda in 'Source\Model\DAO\RPFood.DAO.RestricaoVenda.pas',
  RPFood.View.NovoEndereco in 'Source\View\RPFood.View.NovoEndereco.pas' {FrmNovoEndereco: TIWAppForm},
  RPFood.View.BuscarEndereco in 'Source\View\RPFood.View.BuscarEndereco.pas' {FrmBuscarEndereco: TIWAppForm},
  RPFood.Entity.Configuracao.PagamentoMercadoPago in 'Source\Model\Entity\RPFood.Entity.Configuracao.PagamentoMercadoPago.pas',
  RPFood.DAO.Configuracao.PagamentoMercadoPago in 'Source\Model\DAO\RPFood.DAO.Configuracao.PagamentoMercadoPago.pas',
  RPFood.Migrations.Init in 'Migrations\RPFood.Migrations.Init.pas',
  RPFood.Migrations.M0000001.EmpresaCriarTabela in 'Migrations\RPFood.Migrations.M0000001.EmpresaCriarTabela.pas',
  RPFood.View.Pedido.Pagamento in 'Source\View\RPFood.View.Pedido.Pagamento.pas' {FrmPedidoPagamentoOnline: TIWAppForm},
  RPFood.Service.Pagamento in 'Source\Model\Service\Pagamento\RPFood.Service.Pagamento.pas',
  RPFood.Migrations.M0000002.AddFormaPagamentoOnline in 'Migrations\RPFood.Migrations.M0000002.AddFormaPagamentoOnline.pas',
  RPFood.Migrations.M0000003.PagamentoOnline in 'Migrations\RPFood.Migrations.M0000003.PagamentoOnline.pas',
  RPFood.Entity.PagamentoOnline in 'Source\Model\Entity\RPFood.Entity.PagamentoOnline.pas',
  RPFood.DAO.PagamentoOnline in 'Source\Model\DAO\RPFood.DAO.PagamentoOnline.pas';

{$R *.res}

begin
{$IFDEF DEBUG}
  ReportMemoryLeaksOnShutdown := True;
{$ENDIF}

  StartMigration;
  TIWStart.Execute(True);
end.
